name: create and publish production image

on:
  push:
    branches:
      - "main"

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - run: npm ci
      - run: npm run lint
      
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - run: npm ci
      - run: npm run lint
      
  publish-docker-container:
    name: Build and Publish Docker Container
    needs: [lint-frontend, lint-backend]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: |
            ghcr.io/eerikas/weather-app:latest
            ghcr.io/eerikas/weather-app:0.${{ github.run_number }}
  # Based on:
  # https://cloud.google.com/community/tutorials/cicd-cloud-run-github-actions
  deploy:
    name: Deploy to Google Cloud Run
    needs: [lint-frontend, lint-backend]
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
    steps:
    
    # Deprecated: 
    # - name: Login
    #   uses: google-github-actions/setup-gcloud@v0
    #   with:
    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
    #     service_account_email: ${{ secrets.GCP_EMAIL }}
    #     service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: 'Login'
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . -t $IMAGE_NAME

    - name: Push Docker image
      run: docker push $IMAGE_NAME

    - name: Deploy Docker image
      run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region europe-north1 --set-env-vars=APPID=${{ secrets.APPID }} --max-instances=15 --platform=managed --allow-unauthenticated 
      
